### ISSUE TITLE
two graphical glitches

### ISSUE THREAD

**Issue by nobanzai** [phpbg/muspnp#6]
I found two more grapical glichtes in muspnp:
![image](https://user-images.githubusercontent.com/10534549/162700083-3c52a4e3-f176-4593-990e-f061337d4e9b.png)

As you can see, some of the folder icons are broken.
Maybe there are picture files in those folders an muspnp tries to display them, but is failing?

![image](https://user-images.githubusercontent.com/10534549/162700426-9e54ec23-9b82-40cf-83af-7d8ddfaa5b39.png)

When muspnp started playing, the play and the stop buttons look really ugly as you can see above.

**Comment by phpbg** [comment]
Can you provide a log for this one too?

thx

**Comment by nobanzai** [comment]
Here we go.
[muspnp.zip](https://github.com/phpbg/muspnp/files/8464097/muspnp.zip)

**Comment by phpbg** [comment]
The album art should be fixed in latest release. Can you check?

**Comment by nobanzai** [comment]
Most album icons are now shown instead of the broken icon, but not all - the icon for Aerosmtih for example is still broken.
![image](https://user-images.githubusercontent.com/10534549/162921075-a41622ee-2f60-43fb-a44f-3910ee8e983e.png)

And: Would it be possible to leave some space between the icon and the text?
Thx!

**Comment by phpbg** [comment]
According to your logs, Aerosmith art icon is here : http://192.168.1.8:55555/content/media/object_id/43879/res_id/1/rct/aa

Can you open this url in a web browser on your local network and tell me if an image loads? If yes, what kind of image is this (jpeg, png, ...)?

**Comment by nobanzai** [comment]
I get "404 Not Found".
I am not sure, what file Gerbera references here. The main folder "Aerosmtih" doesn't contain any files, but all of the subfolders for the albums are containing a cover.jpg and a cdart.png file each.

![image](https://user-images.githubusercontent.com/10534549/163668747-5951df63-40e9-474c-b2a0-a475ea3e83b4.png)

**Comment by phpbg** [comment]
Can you try with another upnp player ? I know [bubble for android](https://play.google.com/store/apps/details?id=com.bubblesoft.android.bubbleupnp&hl=fr&gl=US) shows cover/art pictures too.

This will help tell us if it's gerbera or muspnp's fault

**Comment by nobanzai** [comment]
UPPlay shows the icon:

![image](https://user-images.githubusercontent.com/10534549/163707700-2659c973-74b6-4ba5-ae4e-59eee634e36f.png)

And it is the icon from the album "1973- Aerosmith":

![image](https://user-images.githubusercontent.com/10534549/163707734-60f18bc6-bec6-4e09-a910-e04ca9c53e16.png)
